"""initial_tables

Revision ID: 58c88342d2f2
Revises: 
Create Date: 2026-03-22 00:52:26.316777
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Идентификаторы ревизии
revision: str = '58c88342d2f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlab_projects',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID проекта в GitLab'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название проекта'),
    sa.Column('path_with_namespace', sa.String(length=500), nullable=False, comment='Полный путь (namespace/project)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('web_url', sa.String(length=1000), nullable=True, comment='URL проекта в GitLab'),
    sa.Column('visibility', sa.String(length=50), nullable=False, comment='Видимость (private/internal/public)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='Последняя активность'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True, comment='Дата последней синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gitlab_users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID пользователя в GitLab'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Логин'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Полное имя'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email'),
    sa.Column('state', sa.String(length=50), nullable=False, comment='Статус (active/blocked)'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Является ли администратором'),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True, comment='URL аватара'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Дата создания в GitLab'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='Последняя активность'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True, comment='Дата последней синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Начало синхронизации'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Конец синхронизации'),
    sa.Column('date_from', sa.Date(), nullable=False, comment='Начало периода'),
    sa.Column('date_to', sa.Date(), nullable=False, comment='Конец периода'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус (running/completed/failed)'),
    sa.Column('entities_synced', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Счётчики по типам сущностей'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False, comment='SHA хэш коммита'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID проекта'),
    sa.Column('author_name', sa.String(length=255), nullable=False, comment='Имя автора коммита'),
    sa.Column('author_email', sa.String(length=255), nullable=False, comment='Email автора коммита'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Привязка к пользователю GitLab'),
    sa.Column('message', sa.Text(), nullable=True, comment='Сообщение коммита'),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False, comment='Дата коммита'),
    sa.Column('additions', sa.Integer(), nullable=False, comment='Добавленные строки'),
    sa.Column('deletions', sa.Integer(), nullable=False, comment='Удалённые строки'),
    sa.ForeignKeyConstraint(['project_id'], ['gitlab_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gitlab_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha')
    )
    op.create_index('ix_commits_committed_at', 'commits', ['committed_at'], unique=False)
    op.create_index('ix_commits_project_id', 'commits', ['project_id'], unique=False)
    op.create_index('ix_commits_user_id', 'commits', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID события в GitLab'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Автор'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='ID проекта'),
    sa.Column('action_name', sa.String(length=100), nullable=False, comment='Тип действия (pushed/commented/...)'),
    sa.Column('target_type', sa.String(length=100), nullable=True, comment='Тип объекта'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='ID объекта'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата события'),
    sa.ForeignKeyConstraint(['project_id'], ['gitlab_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gitlab_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_user_id', 'events', ['user_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID задачи в GitLab'),
    sa.Column('iid', sa.Integer(), nullable=False, comment='Номер задачи в проекте'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID проекта'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='Автор'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='Ответственный'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Заголовок'),
    sa.Column('state', sa.String(length=50), nullable=False, comment='Статус (opened/closed)'),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Метки'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Дата обновления'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата закрытия'),
    sa.Column('user_notes_count', sa.Integer(), nullable=False, comment='Количество комментариев'),
    sa.ForeignKeyConstraint(['assignee_id'], ['gitlab_users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['gitlab_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['gitlab_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_author_id', 'issues', ['author_id'], unique=False)
    op.create_index('ix_issues_created_at', 'issues', ['created_at'], unique=False)
    op.create_index('ix_issues_project_id', 'issues', ['project_id'], unique=False)
    op.create_table('merge_requests',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID MR в GitLab'),
    sa.Column('iid', sa.Integer(), nullable=False, comment='Номер MR в проекте'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID проекта'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='Автор'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='Ответственный'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Заголовок'),
    sa.Column('state', sa.String(length=50), nullable=False, comment='Статус (opened/closed/merged)'),
    sa.Column('source_branch', sa.String(length=255), nullable=True, comment='Исходная ветка'),
    sa.Column('target_branch', sa.String(length=255), nullable=True, comment='Целевая ветка'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Дата обновления'),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True, comment='Дата мержа'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата закрытия'),
    sa.Column('user_notes_count', sa.Integer(), nullable=False, comment='Количество комментариев'),
    sa.ForeignKeyConstraint(['assignee_id'], ['gitlab_users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['gitlab_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['gitlab_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mr_author_id', 'merge_requests', ['author_id'], unique=False)
    op.create_index('ix_mr_created_at', 'merge_requests', ['created_at'], unique=False)
    op.create_index('ix_mr_project_id', 'merge_requests', ['project_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID комментария в GitLab'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='Автор'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID проекта'),
    sa.Column('noteable_type', sa.String(length=50), nullable=False, comment='Тип сущности (MergeRequest/Issue)'),
    sa.Column('noteable_id', sa.Integer(), nullable=False, comment='ID сущности'),
    sa.Column('body_length', sa.Integer(), nullable=False, comment='Длина текста комментария'),
    sa.Column('system', sa.Boolean(), nullable=False, comment='Системный комментарий'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['author_id'], ['gitlab_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['gitlab_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_author_id', 'notes', ['author_id'], unique=False)
    op.create_index('ix_notes_created_at', 'notes', ['created_at'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='ID пайплайна в GitLab'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='ID проекта'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Кто запустил'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус (success/failed/canceled/...)'),
    sa.Column('ref', sa.String(length=255), nullable=True, comment='Ветка или тег'),
    sa.Column('sha', sa.String(length=40), nullable=True, comment='SHA коммита'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Длительность в секундах'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Дата завершения'),
    sa.ForeignKeyConstraint(['project_id'], ['gitlab_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gitlab_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipelines_created_at', 'pipelines', ['created_at'], unique=False)
    op.create_index('ix_pipelines_user_id', 'pipelines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipelines_user_id', table_name='pipelines')
    op.drop_index('ix_pipelines_created_at', table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index('ix_notes_created_at', table_name='notes')
    op.drop_index('ix_notes_author_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_mr_project_id', table_name='merge_requests')
    op.drop_index('ix_mr_created_at', table_name='merge_requests')
    op.drop_index('ix_mr_author_id', table_name='merge_requests')
    op.drop_table('merge_requests')
    op.drop_index('ix_issues_project_id', table_name='issues')
    op.drop_index('ix_issues_created_at', table_name='issues')
    op.drop_index('ix_issues_author_id', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_events_user_id', table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_commits_user_id', table_name='commits')
    op.drop_index('ix_commits_project_id', table_name='commits')
    op.drop_index('ix_commits_committed_at', table_name='commits')
    op.drop_table('commits')
    op.drop_table('sync_log')
    op.drop_table('gitlab_users')
    op.drop_table('gitlab_projects')
    # ### end Alembic commands ###
